const colors = {
  // light theme
  PRIMARY_COLOR: "#8843CF",
  SECONDARY_COLOR: "#24262d",
  BACKGROUND_COLOR: "#F7F7F7",
  WHITE_COLOR: "#FFFEFF",

  //dark theme
  DARK_PRIMARY_COLOR: "#4344EB",
  LIGHT_GRAY_COLOR: " #d3d3d3",
  EXTRA_LIGHT_GRAY_COLOR: "#eeeeee",
  DARK_GRAY_COLOR: "#8f8f8f",
  WARNING_COLOR: "#FEECDC",
  WARNING_TEXT_COLOR: "#B43403",
  RED_COLOR: "red",
  LINK_COLOR: "#0000FF",
  LINK_HIGHLIGHT_COLOR: "#000099",
};

export default colors;
