const colors = {
  // light theme 
  PRIMARY_COLOR: "#8843CF",
  SECONDARY_COLOR: "#24262d",
  BACKGROUND_COLOR: "#F3F5FA",
  WHITE_COLOR: "#FFFEFF",

  LIGHT_GRAY_COLOR: " #d3d3d3",
  DARK_GRAY_COLOR: "#8f8f8f",
  WARNING_COLOR: "#FEECDC",
  WARNING_TEXT_COLOR: "#B43403",
  RED_COLOR: "red",
  LINK_COLOR: "#0000FF",
  LINK_HIGHLIGHT_COLOR: "#000099",
};

export default colors;
